org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Forge info
minecraft_version=1.20
minecraft_version_range=[1.20]
forge_version=46.0.14
forge_version_range=[46,)
loader_version_range=[46,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Mod info
mod_id=myths_awakening
mod_name=Myths Awakening
mod_license=BSD 3-Clause (NewBSD) License
mod_version=0.0.1
mod_group_id=com.github.imagineforgee
mod_authors=ImagineForgee
mod_description=Adds remodel and retextured designs from different boss from different mods

# Deps
geckolib_version=4.2